# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampledotcom',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exampledotcom',
            name='title',
            field=models.TextField(),
        ),
    ]
