# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170425_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField(default='Default')),
                ('topic', models.TextField(default='Default')),
                ('url', models.TextField(default='Default')),
                ('information', models.TextField(default='Default')),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleDotCom',
        ),
    ]
