# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170430_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField(default='Default')),
                ('topic', models.TextField(default='Default')),
                ('url', models.TextField(default='Default')),
                ('information', models.TextField(default='Default')),
            ],
        ),
    ]
