# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_scrapedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapedimage',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='scrapedimage',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
