# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_classifieddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifieddata',
            name='classification',
            field=models.TextField(default='Default'),
        ),
    ]
