# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_scrapedimage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='metadata',
            field=models.TextField(default='Default'),
        ),
        migrations.AddField(
            model_name='scrapedimage',
            name='metadata',
            field=models.TextField(default='Default'),
        ),
    ]
