# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_trainingdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField(default='Default')),
                ('topic', models.TextField(default='Default')),
                ('url', models.TextField(default='Default')),
                ('information', models.TextField(default='Default')),
            ],
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='description',
            field=models.TextField(default='Descripción de la Data de entrenamiento contenida en el documento'),
        ),
    ]
