# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170616_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='data_entrenamiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingdocument',
            name='description',
            field=models.TextField(default='Descripcion de la Data de entrenamiento contenida en el documento'),
        ),
    ]
