# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20170624_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='Default')),
                ('propagacion_interna', models.BooleanField(default=False)),
            ],
        ),
    ]
